package dev.nordfjell.guard;

import java.util.List;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OrdinaryPredictorTest {
    private static final OrdinaryPhysics.State REST = new OrdinaryPhysics.State(0, -.08 * .98f, 0, 0);
    private static final Geometry.Box FLOOR = new Geometry.Box(-1024, 0, -1024, 1024, 1, 1024);
    private static final CollisionPhysics.Scene FLAT = new CollisionPhysics.Scene(List.of(FLOOR));
    private static final OrdinaryPhysics.Input FORWARD = new OrdinaryPhysics.Input(0, 1, false);

    private static OrdinaryPhysics.Context context(boolean ground, boolean sprint) {
        return new OrdinaryPhysics.Context(ground, sprint, 0, sprint ? .13f : .1f,
                .42f, .08, .6f, 1, 1, 1, .3f, false);
    }
    private static OrdinaryPredictor predictor() {
        var result = new OrdinaryPredictor(); result.seed(.5, 1, .5, REST, true); return result;
    }
    private static OrdinaryPredictor.Frame frame(Avatar avatar) {
        return new OrdinaryPredictor.Frame(avatar.x, avatar.y, avatar.z, 0, true);
    }

    /** Synthetic legal trajectories generated by the separately tested arithmetic kernels. */
    private record Avatar(double x, double y, double z, OrdinaryPhysics.State velocity, boolean ground) {
        Avatar advance(OrdinaryPhysics.Input input, boolean sprint, CollisionPhysics.Scene scene) {
            var context = context(ground, sprint);
            var free = OrdinaryPhysics.step(velocity, input, context);
            var motion = new CollisionPhysics.Motion(free.dx(), free.dy(), free.dz());
            var body = new Geometry.Box(x - .3, y, z - .3, x + .3, y + 1.8, z + .3);
            var collision = CollisionPhysics.move(body, motion, motion, ground, .6f, scene);
            float friction = ground ? OrdinaryPhysics.modifiedFriction(context.blockFriction(), context.frictionModifier()) : 1;
            float horizontalDrag = friction * OrdinaryPhysics.modifiedFriction(.91f, context.airDragModifier());
            float verticalDrag = OrdinaryPhysics.modifiedFriction(.98f, context.airDragModifier());
            var next = new OrdinaryPhysics.State(collision.velocity().x() * horizontalDrag,
                    (collision.velocity().y() - context.gravity()) * verticalDrag,
                    collision.velocity().z() * horizontalDrag, free.next().jumpDelay());
            return new Avatar(x + collision.displacement().x(), y + collision.displacement().y(),
                    z + collision.displacement().z(), next, collision.ground());
        }
    }

    private static void legalTrajectory(OrdinaryPhysics.Input input, boolean sprint, CollisionPhysics.Scene scene) {
        var model = predictor(); var avatar = new Avatar(.5, 1, .5, REST, true);
        for (int tick = 0; tick < 300; tick++) {
            avatar = avatar.advance(input, sprint, scene);
            var result = model.accept(frame(avatar), context(false, sprint), scene, .6f);
            assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status(), "tick=" + tick + ", " + result);
            assertTrue(result.candidates() == 18 || result.candidates() == OrdinaryPredictor.MAX_CANDIDATES);
            assertTrue(model.branches() <= 2); assertTrue(result.error() <= .003);
            assertEquals(avatar.x, model.x(), 1E-7); assertEquals(avatar.y, model.y(), 1E-7);
            assertEquals(avatar.z, model.z(), 1E-7);
        }
    }

    @Test void legalCardinalWalkingFor300Ticks() { legalTrajectory(FORWARD, false, FLAT); }
    @Test void legalDiagonalWalkingFor300Ticks() {
        legalTrajectory(new OrdinaryPhysics.Input(1, 1, false), false, FLAT);
    }
    @Test void legalSprintJumpingFor300Ticks() {
        legalTrajectory(new OrdinaryPhysics.Input(0, 1, true), true, FLAT);
    }
    @Test void legalMovementIntoFullWallFor300Ticks() {
        legalTrajectory(new OrdinaryPhysics.Input(1, 0, false), false,
                new CollisionPhysics.Scene(List.of(FLOOR, new Geometry.Box(3, 1, -20, 4, 4, 20))));
    }
    @Test void legalSlabStepAndDescentFor300Ticks() {
        legalTrajectory(new OrdinaryPhysics.Input(1, 0, false), false,
                new CollisionPhysics.Scene(List.of(FLOOR, new Geometry.Box(3, 1, -20, 5, 1.5, 20))));
    }

    @Test void indistinguishableWalkAndJumpStepRetainBothGroundStates() {
        var scene = new CollisionPhysics.Scene(List.of(FLOOR, new Geometry.Box(3, 1, -20, 5, 1.5, 20)));
        for (boolean jumpAtStep : new boolean[]{false, true}) {
            var model = predictor(); var avatar = new Avatar(.5, 1, .5, REST, true);
            boolean bankUsed = false, bankResolved = false;
            for (int tick = 0; tick < 30; tick++) {
                avatar = avatar.advance(new OrdinaryPhysics.Input(1, 0, jumpAtStep && tick == 11), false, scene);
                var result = model.accept(frame(avatar), context(false, false), scene, .6f);
                assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status(), "jump=" + jumpAtStep + ", tick=" + tick);
                assertEquals(avatar.x, model.x(), 1E-7); assertEquals(avatar.y, model.y(), 1E-7);
                if (tick == 11) {
                    assertEquals(!jumpAtStep, avatar.ground);
                    assertEquals(2, model.branches()); bankUsed = true;
                }
                if (tick == 12) {
                    assertEquals(36, result.candidates()); assertEquals(1, model.branches()); bankResolved = true;
                }
            }
            assertTrue(bankUsed); assertTrue(bankResolved);
        }
    }

    @Test void speedMultiplierCannotBecomePredictedVelocity() {
        var model = predictor(); var avatar = new Avatar(.5, 1, .5, REST, true);
        double cheatedZ = .5, lastLegalZ = .5;
        for (int tick = 0; tick < 20; tick++) {
            avatar = avatar.advance(FORWARD, true, FLAT);
            cheatedZ += (avatar.z - lastLegalZ) * 2.5; lastLegalZ = avatar.z;
            var result = model.accept(new OrdinaryPredictor.Frame(.5, 1, cheatedZ, 0, true),
                    context(true, true), FLAT, .6f);
            assertEquals(OrdinaryPredictor.Status.REJECT, result.status());
            assertEquals(tick + 1, result.consecutiveRejected());
            assertNotEquals(cheatedZ, model.z()); assertTrue(model.z() < cheatedZ);
        }
    }

    @Test void tinyPerFrameCreepExhaustsAbsoluteTolerance() {
        var model = predictor(); var avatar = new Avatar(.5, 1, .5, REST, true);
        boolean rejected = false;
        for (int tick = 1; tick <= 100; tick++) {
            avatar = avatar.advance(FORWARD, false, FLAT);
            double observedZ = avatar.z + tick * .0001;
            var result = model.accept(new OrdinaryPredictor.Frame(avatar.x, avatar.y, observedZ, 0, true),
                    context(true, false), FLAT, .6f);
            assertNotEquals(OrdinaryPredictor.Status.DEFER, result.status());
            if (result.status() == OrdinaryPredictor.Status.REJECT) {
                rejected = true; assertTrue(result.error() > .003); assertTrue(tick <= 31); break;
            }
            assertEquals(avatar.z, model.z(), 1E-7);
        }
        assertTrue(rejected, "Observed tolerance must not become free displacement each frame");
    }

    @Test void missingPositionsUsePersistentReportedAnchor() {
        var model = predictor();
        for (int tick = 1; tick <= 300; tick++) {
            boolean reminder = tick % 20 == 0;
            var frame = new OrdinaryPredictor.Frame(reminder ? .5 : Double.NaN,
                    reminder ? 1 : Double.NaN, reminder ? .5 : Double.NaN, 0, reminder);
            var result = model.accept(frame, context(true, false), FLAT, .6f);
            assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status()); assertEquals(0, result.error());
        }
    }

    @Test void missingPositionCannotFreezeEstablishedMomentum() {
        var model = predictor(); model.seed(.5, 1, .5, new OrdinaryPhysics.State(.4, -.08 * .98f, 0, 0), true);
        var result = model.accept(new OrdinaryPredictor.Frame(Double.NaN, Double.NaN, Double.NaN, 0, false),
                context(true, false), FLAT, .6f);
        assertEquals(OrdinaryPredictor.Status.REJECT, result.status());
        assertTrue(model.x() > .5); assertTrue(result.error() > .0002);
    }

    @Test void clientGroundClaimCannotReplaceInternalGround() {
        var model = new OrdinaryPredictor(); model.seed(.5, 3, .5, new OrdinaryPhysics.State(0, 0, 0, 0), false);
        var result = model.accept(new OrdinaryPredictor.Frame(.5, 3, .5 + (double) .98f * .02f, 0, true),
                context(true, false), new CollisionPhysics.Scene(List.of()), .6f);
        assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status()); assertFalse(model.ground());
    }

    @Test void unknownContextClearsHistoryWithoutViolation() {
        var model = predictor();
        var result = model.accept(new OrdinaryPredictor.Frame(.5, 1, .5, 0, true), null, FLAT, .6f);
        assertEquals(OrdinaryPredictor.Status.DEFER, result.status()); assertFalse(model.seeded());
        assertEquals(0, result.consecutiveRejected()); assertNull(model.position());
    }

    @Test void initialPenetrationDefersWithoutSeedingFromObservedPosition() {
        var model = predictor();
        var inside = new CollisionPhysics.Scene(List.of(new Geometry.Box(0, 1, 0, 1, 3, 1)));
        var result = model.accept(new OrdinaryPredictor.Frame(200, 1, 200, 0, true), context(true, false), inside, .6f);
        assertEquals(OrdinaryPredictor.Status.DEFER, result.status()); assertFalse(model.seeded());
        assertEquals(1, result.candidates());
    }

    @Test void ambiguousLowAccelerationDefersInsteadOfChoosingUnprovenState() {
        var model = predictor();
        var slow = new OrdinaryPhysics.Context(true, false, 0, .001f, .42f, .08, .6f, 1, 1, 1, .3f, false);
        var result = model.accept(new OrdinaryPredictor.Frame(.5, 1, .50098, 0, true), slow, FLAT, .6f);
        assertEquals(OrdinaryPredictor.Status.DEFER, result.status()); assertEquals("ambiguous_candidate_states", result.reason());
        assertFalse(model.seeded());
    }

    @Test void trustedReseedClearsRejectionHistory() {
        var model = predictor();
        assertEquals(OrdinaryPredictor.Status.REJECT, model.accept(new OrdinaryPredictor.Frame(90, 1, 90, 0, true),
                context(true, false), FLAT, .6f).status());
        model.seed(.5, 1, .5, REST, true);
        var result = model.accept(new OrdinaryPredictor.Frame(.5, 1, .5, 0, true), context(true, false), FLAT, .6f);
        assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status()); assertEquals(0, result.consecutiveRejected());
    }

    @Test void boundedSyntheticSixHundredModelWorkload() {
        var models = new OrdinaryPredictor[600];
        for (int i = 0; i < models.length; i++) models[i] = predictor();
        var avatar = new Avatar(.5, 1, .5, REST, true);
        long start = System.nanoTime();
        for (int tick = 0; tick < 60; tick++) {
            avatar = avatar.advance(FORWARD, false, FLAT);
            var frame = frame(avatar); var attributes = context(true, false);
            for (var model : models) {
                var result = model.accept(frame, attributes, FLAT, .6f);
                assertEquals(OrdinaryPredictor.Status.ACCEPT, result.status()); assertEquals(18, result.candidates());
            }
        }
        long elapsed = System.nanoTime() - start;
        System.out.println("NORD_PREDICTOR_WORKLOAD: 36000 frames, 648000 candidate trials, elapsed ms="
                + elapsed / 1_000_000 + "; excludes world collection, packets, schedulers and real clients");
    }
}
