package dev.nordfjell.guard;

public enum Check {
    FLIGHT, SPIDER, SPEED, HIGHJUMP, WATERWALK, CLIMB, NOWEB, NOSLOW, NOCLIP, NOFALL,
    REACH, WALLHIT, ATTACKRATE, BLOCKREACH, FASTBREAK, BREAKRATE, PLACERATE
}
